// Embeds the sample PDFs as base64 so the demo works offline and inside a single-file build.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
const files = readdirSync('samples').filter((f) => f.endsWith('.pdf')).sort();
const meta = {
  'Access_Control_Policy.pdf': 'Policy describing access rules. Used in the 2-minute demo.',
  'Incident_Response_Plan.pdf': 'Draft plan with roles and steps, never exercised.',
  'Backup_Restore_Test_Report.pdf': 'Record of a real restore test: operating evidence.',
  'Supplier_Note_untrusted.pdf': 'Untrusted file with a prompt-injection attempt (security test).',
};
const order = ['Access_Control_Policy.pdf', 'Incident_Response_Plan.pdf', 'Backup_Restore_Test_Report.pdf', 'Supplier_Note_untrusted.pdf'];
files.sort((a, b) => order.indexOf(a) - order.indexOf(b));
const entries = files.map((f) => `  { name: ${JSON.stringify(f)}, description: ${JSON.stringify(meta[f] ?? '')}, base64: ${JSON.stringify(readFileSync('samples/' + f).toString('base64'))} },`);
writeFileSync('src/data/samples.ts', `// GENERATED by scripts/embed_samples.mjs. Fictional documents.\nexport const SAMPLE_DOCS: { name: string; description: string; base64: string }[] = [\n${entries.join('\n')}\n];\n`);
console.log('embedded', files.length, 'samples');
